### ISSUE TITLE
Bloom filter unused or expired tokens clearing or garbage collector 

### ISSUE THREAD

**Issue by vnuko** [devopsfaith/bloomfilter#7]
Is there currently any way to clear or to remove old tokens, for example tokens which are already expired, from the bloom filter? I didn't find any notes or documentation about this. It would be nice to have a script which might be running on regular times to remove all the tokens based on some criteria e.g where the date is expired.

**Comment by kpacha** [comment]
no, there is no way to remove elements from the bloomfilter.

That's why we added the `rotate` pkg, so 3 instances are used and they are rotated every TTL (should be the same TTL your tokens have). At every rotation, the oldest bloomfilter is removed and a fresh one is added to the data structure
